# Generated by Django 4.1.12 on 2024-11-10 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='displayname',
            field=models.CharField(default='Unnamed', max_length=100, verbose_name='Full Name'),
        ),
    ]
