# Generated by Django 4.1.12 on 2024-11-10 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0002_employee_displayname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaborate',
            name='employee',
        ),
        migrations.AddField(
            model_name='collaborate',
            name='employees',
            field=models.ManyToManyField(to='hrms.employee', verbose_name='Employees'),
        ),
    ]
